apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: analytics-for-spotify-ci
resources:
  #- image-build-pipeline.yaml
  - unit-test.yaml
  #- pipeline.yaml
  - rbac.yaml
  - repo.yaml
  #- triggers/event-listener.yaml
  #- triggers/binding.yaml
  #- triggers/template.yaml
  #- triggers/route.yaml
  - knative-rbac.yaml
  - push-secret.yaml
  - namespace.yaml
  - network-policy.yaml
  - limit-range.yaml
