apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: analytics-for-spotify-ext
  namespace: analytics-for-spotify-ext
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: https-gateway-external
      namespace: openshift-ingress
  hostnames:
    - analytics-for-spotify.arthurvardevanyan.com
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: analytics-for-spotify
          namespace: analytics-for-spotify-ext
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
    - filters:
        - requestRedirect:
            port: 443
            scheme: https
            statusCode: 301
          type: RequestRedirect
      matches:
        - path:
            type: PathPrefix
            value: /
