apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: analytics-for-spotify-cert
  namespace: analytics-for-spotify-ext
spec:
  secretName: analytics-for-spotify-cert
  duration: 2160h # 90d
  renewBefore: 1080h # 45d
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
  dnsNames:
    - "analytics-for-spotify.arthurvardevanyan.com"
    # - "spotify.arthurvardevanyan.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
